// Date: 09/07/2013 14:21:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package piefarmer.immunology.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGlider extends ModelBiped
{
  //fields
    ModelRenderer Chest;
    ModelRenderer FrontRightStrut;
    ModelRenderer FrontLeftStrut;
    ModelRenderer MiddleStrut;
    ModelRenderer FrameLeft;
    ModelRenderer FrameRight;
    ModelRenderer Wing;
  
  public ModelGlider()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Chest = new ModelRenderer(this, 15, 2);
      Chest.addBox(0F, 0F, 0F, 8, 8, 6);
      Chest.setRotationPoint(-4F, 0F, -3F);
      Chest.setTextureSize(256, 128);
      Chest.mirror = true;
      setRotation(Chest, 0F, 0F, 0F);
      FrontRightStrut = new ModelRenderer(this, 10, 0);
      FrontRightStrut.addBox(-0.5F, -18F, -0.5F, 1, 18, 1);
      FrontRightStrut.setRotationPoint(-3F, 7.5F, -2F);
      FrontRightStrut.setTextureSize(256, 128);
      FrontRightStrut.mirror = true;
      setRotation(FrontRightStrut, 0.3209753F, 1.117011F, 0.1115358F);
      FrontLeftStrut = new ModelRenderer(this, 10, 0);
      FrontLeftStrut.addBox(-0.5F, -18.5F, -0.5F, 1, 18, 1);
      FrontLeftStrut.setRotationPoint(3F, 7.6F, -2F);
      FrontLeftStrut.setTextureSize(256, 128);
      FrontLeftStrut.mirror = true;
      setRotation(FrontLeftStrut, 0.2094395F, 0.1396263F, 0.296706F);
      MiddleStrut = new ModelRenderer(this, 8, 0);
      MiddleStrut.addBox(0F, 0F, -0.5F, 10, 1, 1);
      MiddleStrut.setRotationPoint(-4.9F, -0.9F, -4F);
      MiddleStrut.setTextureSize(256, 128);
      MiddleStrut.mirror = true;
      setRotation(MiddleStrut, 0.3020762F, 0F, 0F);
      FrameLeft = new ModelRenderer(this, 10, 0);
      FrameLeft.addBox(0F, 0F, 0F, 50, 1, 1);
      FrameLeft.setRotationPoint(1F, -10F, -26F);
      FrameLeft.setTextureSize(256, 128);
      FrameLeft.mirror = true;
      setRotation(FrameLeft, 0F, -1.22173F, 0F);
      FrameRight = new ModelRenderer(this, 10, 0);
      FrameRight.addBox(0F, 0F, 0F, 50, 1, 1);
      FrameRight.setRotationPoint(0F, -10F, -25.7F);
      FrameRight.setTextureSize(256, 128);
      FrameRight.mirror = true;
      setRotation(FrameRight, 0F, -1.919862F, 0F);
      Wing = new ModelRenderer(this, 0, 33);
      Wing.addBox(0F, 0F, 0F, 35, 1, 46);
      Wing.setRotationPoint(-17F, -9.5F, -26F);
      Wing.setTextureSize(256, 128);
      Wing.mirror = true;
      setRotation(Wing, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Chest.render(f5);
    FrontRightStrut.render(f5);
    FrontLeftStrut.render(f5);
    MiddleStrut.render(f5);
    FrameLeft.render(f5);
    FrameRight.render(f5);
    Wing.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  public void renderAll()
  {
	  Chest.render(0.0625F);
	  FrontRightStrut.render(0.0625F);
	  FrontLeftStrut.render(0.0625F);
	  MiddleStrut.render(0.0625F);
	  FrameLeft.render(0.0625F);
	  FrameRight.render(0.0625F);
	  Wing.render(0.0625F);
  }

}
